### PR TITLE
fix translation

### PR DESCRIPTION
**Pull request by barisusakli**
translate the output of app.render

### CODE REVIEW

**Comment by TheStranjer** [comment]
I actually tried this exact approach, but it didn't work because it will always translate into the language of the server. So if I, as a user, change my language to Swedish, it will not output Swedish text, but English text.

**Comment by barisusakli** [comment]
Ahh true, the server side doesn't have access to the current user so it doesn't know which language they selected. It should work if ajaxify into a topic that has roll because then it knows the users language setting client side. https://github.com/NodeBB/NodeBB/blob/master/public/src/modules/translator.js#L128-L132

**Comment by barisusakli** [comment]
Ahh I think it defaults to forum language because posts are cached. So if it were to render the post in swedish first all other forum users would see it in swedish instead of the forum default.

**Comment by TheStranjer** [comment]
Yeah, it's a tough one. I actually did put some thought into the sanitization pull request on the actual NodeBB before shipping it out. I've got a decent enough workaround on this one, I just think it would be better if no such workaround was necessary. Hence the pull request on NodeBB's `master`.

**Pull request closed without merging**
